title: Associate Data Analyst Project Portfolio <p>Adrian Sim</p> # your name (or website title) here
logo: "/images/20201209_ 18 Adrian Sim 1_Resized1.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This portfolio is dedicated to the journey for Associate Data Analyst Course
  <br><br>
  I will be featuring the projects that I have done on <strong>Excel Dashboard</strong>, <strong>MS SQL</strong>, <strong>PowerBI</strong> and <strong>Python</strong>
  <br><br>
  <p>
  <a href="https://">View My LinkedIn Profile</a> 
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
