title: Associate Data Analyst Project Portfolio <p></p><p>by Adrian Sim</p> # your name (or website title) here
logo: "/images/DS_images1.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This portfolio is dedicated to the journey for Associate Data Analyst Course
  <br><br>
  I will be featuring the projects that I have done on <strong>Excel Dashboard</strong>, <strong>MS SQL</strong>, <strong>PowerBI</strong> and <strong>Python</strong>
  <br><br>
 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
